# Generated by Django 5.1.7 on 2025-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='token_dispositivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
