# Generated by Django 5.1.7 on 2025-03-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_token_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='token_dispositivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
