# Generated by Django 5.1.7 on 2025-03-29 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_token_dispositivo_to_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='domicilio_atencion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='estado_matricula',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido')], default='vigente', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudreceta',
            name='cantidad_anticonceptivos',
            field=models.IntegerField(default=1, help_text='Cantidad de anticonceptivos (1-3)', validators=[django.core.validators.MinValueValidator(1, message='La cantidad de anticonceptivos debe ser mayor a 0'), django.core.validators.MaxValueValidator(3, message='La cantidad de anticonceptivos no puede ser mayor a 3')]),
        ),
        migrations.AddField(
            model_name='solicitudreceta',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
