# Generated by Django 5.1.7 on 2025-03-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_doctor_domicilio_atencion_doctor_especialidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="doctor_asignado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacientes",
                to="core.doctor",
            ),
        ),
    ]
